# LED
BLUE_CHANNEL = 11
RED_CHANNEL = 13
GREEN_CHANNEL = 15

# Player buttons
PREV_BUTTON_PIN = 37  # GPIO 16
NEXT_BUTTON_PIN = 32  # GPIO 12
PAUSE_BUTTON_PIN = 36 # GPIO 26

INTERRUPT_PIN = 7  # GPIO 4

# Power button
POWER_LED = 3         # GPIO 2
POWER_BUTTON = 5      # GPIO 3